### ISSUE TITLE
ファンサービス

### ISSUE THREAD

**Issue by nnawakearuka** [dialoguedaisuki/DigitalTattooTwitterMedia#10]
ファンに対して特別な対応をする必要はあるのではないかと考えました。

### ファンとは
本システムの仕組みを知りつつ条件に乗っかる方

#### ファンを定義づけるには
例えばツイート内に「〇〇bot」など含む、明らかにこちらのことを知り得た上でツイートをする方　など。
プロフィールに特定のキーワードを含む、などもいいかもしれませんね。
ユーザIDを溜めるのであればn分以内にn件以上の投稿をした場合、なども当てはまりそうです。
[ここ](https://mag.app-liv.jp/archive/81735/)を参考にsince-until検索で実行時間からn時間以内を検索し、
同一アカウントがn個以上見つかったら、でもいいかと。

#### ファンサービス
この場合は以下のようなサービスを複合的に行うのはいかがでしょうか
- 対象となったツイートをスクショ
- 本人のホームをスクショ
- 本人のいいね欄をスクショ
- 本人のフォロー欄をスクショ
- 本文には本人のアカウントの情報（アカウントID、アカウント作成日、総ツイート数など）をツイート

**Comment by trysaildaisuki** [comment]
非常に素晴らしい！最優先でコードにしましょう！

**Comment by trysaildaisuki** [comment]
ヘッドレス実行で難なく画像取得できました。問題はクエリをどうするかですね。

![screenshot](https://user-images.githubusercontent.com/60532865/122005307-7133d700-cdf0-11eb-86ae-a0261694d345.png)

**Comment by nnawakearuka** [comment]
難しいですね、以前でしたらこう言う一回の検索に何件も引っかかる人はもうファンだと思うのですが

![image](https://user-images.githubusercontent.com/27218394/122006217-8a895300-cdf1-11eb-8f7c-d6a778c87eb7.png)

今だとそうですね、例えば本文に「〇〇bot」 & (「注意」 or 「試」(試しに、とか)）」が入っていて、かつ画像なり動画なりが添付されている物なんかはファンなのかなあとか思います。

**Comment by trysaildaisuki** [comment]
なるほど、同じユーザーは1日1回の転載とするので抑制は効きそうですね。今でも相当な数のファンがいらっしゃるので #すぐ消すbotファン博覧会 などのハッシュタグを利用して検索の利便性を高めるのもアリですね。

**Comment by dialoguedaisuki** [comment]
ひとまず要件をコードにしてSTG環境で実行後、本番環境をスタートさせて運用試験を行っています。キャッチアップされた課題を踏まえてcommitしたいと思います。

**Comment by dialoguedaisuki** [comment]
対応完了致しました。

**Comment by dialoguedaisuki** [comment]
動画対応してなかったｗ

**Comment by dialoguedaisuki** [comment]
引数変えるだけだったはｗ
