### ISSUE TITLE
データベースの導入

### ISSUE THREAD

**Issue by nnawakearuka** [dialoguedaisuki/DigitalTattooTwitterMedia#5]
DBを導入し、バイナリ データを保存する。
保存方法は任意

### 実装案
- データベースにBLOBカラムを用意してバイナリを直接データベースに登録する
　　利点：データベース内に全てデータを持つ形になるのでバックアップの取得やサーバ移行時に
　　　　　データベースのデータを丸々移動するだけで終わり手軽。
　問題点：データベースの容量が大きくなる。
　　　　　データベースにバイナリを直接登録するのでデータベースアクセスや更新の負荷が大きい。

-  ファイルをサーバにダウンロードし、ファイル名とパスをデータベースに登録する
　　利点：データベースに最低限の情報しか持たないためデータベースの容量が小さくて住む
　　　　　またデータベースの更新処理に時間もかからない。
　問題点：データベースに登録された内容とファイルサーバ内の構成が紐づいていないと
　　　　　正常に動作しないため、取得したファイルの置き方を考える必要がある。
　　　　　また、データ削除時にデータベースとファイルを同期して消す仕組みが必要になる

**Comment by trysaildaisuki** [comment]
issueありがとうございます。こんなクソシステムに金をかけるのもバカバカしいですね。
現在インフラはGCPですが、Oracle Cloudに移行しようと考えています。[この記事](https://qiita.com/nh321/items/e8c63b02e3fa9c28837f)によるとRDBMSの無料枠は存在しませんが、Ocacle Cloudですと
>Oracle Autonomous Transaction ProcessingまたはOracle Autonomous Data Warehouseを選択できます。合計2つのデータベースのそれぞれに1つのOCPUと20 GBのストレージ。

とあるからです。VMインスタンスも[2つまで無料](https://www.oracle.com/jp/cloud/free/#always-free)ですし、調べてないですが、AWSと比べての安さを売りにしているので、帯域も安そうです。現在インフラはterraformとansibleを使用しているので、最終的にコマンド1発で同じ環境を使えることを理想としたいですね。インフラ関係のレシピはpyよりお粗末なので早めに綺麗にして公開したいです。

**Comment by oyianawamak** [comment]
容量が心配なので出来るのであれば持っているPCにvagrantなんかでpythonとDBなにか(mysqlあたりでいいと思います)
入っている環境作ってそこでpython組んで試してみるといいかなとか思います、
そうするとDBに登録した後にテーブルの容量をみることができるのでそれ見ることで使うであろう帯域も見積もりできるかと
![image](https://user-images.githubusercontent.com/27218394/120804042-278cf600-c57f-11eb-8e65-f9fc8a301587.png)

あとpythonを使ったバイナリのインサートは結構簡単そうですね。
[ここ](https://www.mysqltutorial.org/python-mysql-blob/)みるとサクッとできそう

```
from mysql.connector import MySQLConnection, Error
from python_mysql_dbconfig import read_db_config

def update_blob(author_id, filename):
    # read file
    data = read_file(filename)

    # prepare update query and data
    query = "UPDATE authors " \
            "SET photo = %s " \
            "WHERE id  = %s"

    args = (data, author_id)

    db_config = read_db_config()

    try:
        conn = MySQLConnection(**db_config)
        cursor = conn.cursor()
        cursor.execute(query, args)
        conn.commit()
    except Error as e:
        print(e)
    finally:
        cursor.close()
        conn.close()
```

**Comment by dialoguedaisuki** [comment]
DB何も分からんのでOracle Cloud検証しつつ[こいつ](https://cosol.jp/techdb/2021/04/1z0-082-new-oracle-master-silver-dba-book/)を取る予定、LPICレベル3取れたし行けるという寸法。

**Comment by dialoguedaisuki** [comment]
これで問題ありません。
![image](https://user-images.githubusercontent.com/60532865/151300500-e5853e29-9078-4685-8627-85b317a6ebe0.png)

**Comment by dialoguedaisuki** [comment]
コミットメッセージ間違えたけど対応しました。
https://github.com/dialoguedaisuki/DigitalTattooTwitterMedia/commit/11d63ce5d1e13e5693680d552ac915ca58fd4dfc
rebaseするのめんどくさいのでこのままでいきます。

**Comment by dialoguedaisuki** [comment]
>ファイルをサーバにダウンロードし、ファイル名とパスをデータベースに登録する
　　利点：データベースに最低限の情報しか持たないためデータベースの容量が小さくて住む
　　　　　またデータベースの更新処理に時間もかからない。
　問題点：データベースに登録された内容とファイルサーバ内の構成が紐づいていないと
　　　　　正常に動作しないため、取得したファイルの置き方を考える必要がある。
　　　　　また、データ削除時にデータベースとファイルを同期して消す仕組みが必要になる

djangoの仕様からこちらに変更
https://github.com/dialoguedaisuki/DigitalTattooTwitterMedia/commit/b2bd43165c6a3c21914e2f7a25a4741d5b364aac
